apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-a-bc
  namespace: apps
spec:
  healthCheck:
    type: HTTP
    requestPath: /
    port: 8080
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: app-b-bc
  namespace: apps
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz
    port: 8080
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
